parameters:
  user_permission.author.email: 'devggbb@gmail.com'

services:
  Ggbb\SymfonyUserPermissionBundle\Command\CreateDefaultUserRoleCommand:
    autowire: true
    tags:
      -  { name: console.command }

  user_permission.mapping:
    class: Ggbb\SymfonyUserPermissionBundle\PermissionMapping\PermissionMapping

  user_permission.user_service:
    class: Ggbb\SymfonyUserPermissionBundle\Service\PermissionService
    arguments:
      -
    autowire: true
    autoconfigure: true

  user_permission.user_provider:
    class: Ggbb\SymfonyUserPermissionBundle\Security\Provider\UserProvider
    autowire: true

  user_permission.security.permission_voter:
    class: Ggbb\SymfonyUserPermissionBundle\Security\Voter\PermissionVoter
    tags: ['security.voter']
    arguments:
      - '@user_permission.user_service'
    autowire: true
