parameters:
  ggbb_user_permission.author.email: 'devggbb@gmail.com'

services:
  Ggbb\SymfonyUserPermission\Command\CreateDefaultUserRoleCommand:
    autowire: true
    tags:
      -  { name: console.command }

  Ggbb\SymfonyUserPermission\EventListener\RequestSubscriber:

  ggbb.user_permission.mapping:
    class: Ggbb\SymfonyUserPermission\PermissionMapping\PermissionMapping

  ggbb.user_permission.user_service:
    class: Ggbb\SymfonyUserPermission\Service\PermissionService
    arguments:
      -
    autowire: true
    autoconfigure: true

  ggbb.user_permission.user_provider:
    class: Ggbb\SymfonyUserPermission\Security\Provider\UserProvider
    autowire: true

  ggbb.user_permission.security.permission_voter:
    class: Ggbb\SymfonyUserPermission\Security\Voter\PermissionVoter
    tags: ['security.voter']
    arguments:
      - '@ggbb.user_permission.user_service'
    autowire: true
    autoconfigure: true
