parameters:
  ggbb_user_permission.author.email: 'devggbb@gmail.com'

services:
  Ggbb\SymfonyUserPermission\Command\CreateDefaultUserRoleCommand:
    autowire: true
    tags:
      -  { name: console.command }

  Ggbb\SymfonyUserPermission\Security\UserProvider:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.